name: shorey
description:
  Shorey is a simple note app which is built with Flutter 3 and supports
  both Android/iOS platforms. It provides me full experience of interacting with Flutter
  and in the meantime I hope it can be your knowledge/memory transition tool,
  and yes, there still much work to do.

publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.0-beta.2

environment:
  sdk: ^3.2.0
  flutter: '>=3.6.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.3
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.0.9
  synchronized: ^3.0.0+3
  animated_text_kit: ^4.2.2
  flutter_local_notifications: ^16.1.0
  cupertino_icons: ^1.0.5
  syncfusion_flutter_datepicker: ^23.2.4
  day_night_time_picker: ^1.1.3
  flutter_native_timezone: ^2.0.0
  #  intl: ^0.18.1
  package_info_plus: ^5.0.1
  lottie: ^2.3.2
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.6
  sembast: ^3.4.4
  path_provider: ^2.0.11
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.10
  path: ^1.8.2
  ionicons: ^0.2.1
  dio: ^5.1.2
  linkwell: ^2.0.6
  amap_flutter_location: ^3.0.0
  permission_handler: ^11.0.1
  flutter_qweather: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.2.0+1
  build_runner: ^2.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/anim/
    - assets/icons/material/
    - assets/images/
    - assets/json/
  fonts:
    - family: QWeather
      fonts:
        - asset: assets/fonts/qweather_icons.ttf

  generate: true
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
